system = {
    poll_event         = function(...) end,
    wait_event         = function(timeout) return false end,
    set_cursor         = function(cursor_name) end,
    set_window_title   = function(title) end,
    set_window_mode    = function(mode, width, height) end,
    window_has_focus   = function() return false end,
    show_confirm_dialog= function(title, message) return false end,
    chdir              = function(path) end,
    list_dir           = function(path) return {} end,
    absolute_path      = function(path) return "" end,
    get_file_info      = function(path) return { modified=0, size=0, type="file" } end,
    get_clipboard      = function() return "" end,
    set_clipboard      = function(text) end,
    get_time           = function() return 0 end,
    sleep              = function(seconds) end,
    exec               = function(cmd) end,
    fuzzy_match        = function(str, pattern) return 0 end,
  }