
-- -----------------------------------------------------------------------------------------

local dirtools  = require("tools.vfs.dirtools")
dirtools.init("dim")

--_G.SOKOL_DLL    = "sokol_debug_dll"
local sapp      = require("sokol_app")
sg              = require("sokol_gfx")
sg              = require("sokol_nuklear")
local nk        = sg
local slib      = require("sokol_libs") -- Warn - always after gfx!!

local hmm       = require("hmm")
local hutils    = require("hmm_utils")

local stb       = require("stb")
local utils     = require("utils")

local ffi       = require("ffi")

-- --------------------------------------------------------------------------------------

ARGS = arg 

VERSION     = "1.11"
PLATFORM    = ffi.os.." "..ffi.arch
SCALE       = sapp.sapp_dpi_scale()
EXEFILE     = dirtools.get_app_path()..dirtools.sep.."runner.exe"
-- This is kinda a fake runner name for the timebeing. Not sure if its really needed.
print(EXEFILE)

-- --------------------------------------------------------------------------------------
-- Load in the methods lites registers for rendering and io and such.

require("src.api.api")

local core

-- --------------------------------------------------------------------------------------
local shell32   = ffi.load("shell32")

ffi.cdef[[
    void Sleep(uint32_t ms);
    void *  ShellExecuteA(const void * hwnd, const char * lpOperation, const char * lpFile, const char * lpParameters, char* lpDirectory, int nShowCmd);
    int ShowWindow(const void * hWnd, int nCmdShow);
]]

local SW_MAXIMIZE = 3

-- --------------------------------------------------------------------------------------
local enabled_profile   = arg[1] == "-profile"
local profile           = nil
if(enabled_profile) then 
    profile = require("jit.profile")
    function cb(thread, samples, vmstate)
        print(profile.dumpstack(thread, "l\n", 1))
    end
    profile.start("fi4", cb)
end

-- --------------------------------------------------------------------------------------

local width = 1920 
local height = 1080
if(arg[1] and arg[2]) then 
    width = tonumber(arg[1])
    height = tonumber(arg[2])
end
print("Display: "..width .. " x ".. height)

-- --------------------------------------------------------------------------------------

local function ErrorCheck(status, err)
    if(status == false) then 
        print(status)
        print(err)
        print(debug.traceback())
        os.exit()
    end
end

-- --------------------------------------------------------------------------------------

local function init()

    local desc = ffi.new("sg_desc[1]")
    desc[0].environment = slib.sglue_environment()
    desc[0].logger.func = slib.slog_func
    desc[0].disable_validation = false
    sg.sg_setup( desc )

    local snk = ffi.new("snk_desc_t[1]")
    snk[0].dpi_scale = sapp.sapp_dpi_scale()
    snk[0].logger.func = slib.slog_func
    nk.snk_setup(snk)

    print("Sokol Is Valid: "..tostring(sg.sg_isvalid()))

    core = nil

    sapp.sapp_show_mouse(true)
    sapp.sapp_set_window_title("Dim v"..VERSION.."["..PLATFORM.."]")

    local hwnd = sapp.sapp_win32_get_hwnd()
    ffi.C.ShowWindow(hwnd, SW_MAXIMIZE)
end

-- --------------------------------------------------------------------------------------

local function input(event) 

    -- Only kick things off once the window is ready.
    if(event.type == sapp.SAPP_EVENTTYPE_RESIZED) then 
        local w         = sapp.sapp_widthf()
        local h         = sapp.sapp_heightf()   
        -- core resize?
    end

end

-- -----------------------------------------------------------------------------------------

local function core_init()
    SCALE = tonumber(os.getenv("LITE_SCALE")) or SCALE
    PATHSEP = package.config:sub(1, 1)
    EXEDIR = EXEFILE:match("^(.+)[/\\\\].*$")
    package.path = EXEDIR .. '/data/?.lua;' .. package.path
    package.path = EXEDIR .. '/data/?/init.lua;' .. package.path
    core = require('core')
    core.init()
end

-- --------------------------------------------------------------------------------------

local function frame()

    -- /* NOTE: the vs_params_t struct has been code-generated by the shader-code-gen */
    local w         = sapp.sapp_widthf()
    local h         = sapp.sapp_heightf()
    local t         = (sapp.sapp_frame_duration() * 60.0)

    local dt = sapp.sapp_frame_duration()
    local ctx = nk.snk_new_frame()

    renderer.ctx    = ctx 
    
    if(core == nil) then     
        ErrorCheck( pcall( core_init, w, h ) )
        nk.nk_style_show_cursor(ctx)   
    else
        ErrorCheck( pcall( core.run ) )
    end

    -- // the sokol_gfx draw pass
    local pass = ffi.new("sg_pass[1]")
    pass[0].action.colors[0].load_action = sg.SG_LOADACTION_CLEAR
    pass[0].action.colors[0].clear_value = { 0.25, 0.5, 0.7, 1.0 }
    pass[0].swapchain = slib.sglue_swapchain()
    sg.sg_begin_pass(pass)

    nk.snk_render(sapp.sapp_width(), sapp.sapp_height())
    sg.sg_end_pass()
    sg.sg_commit()

    -- Display frame stats in console.
    -- hutils.show_stats()
end

-- --------------------------------------------------------------------------------------

local function cleanup()
    nk.snk_shutdown()
    sg.sg_shutdown()
end

-- --------------------------------------------------------------------------------------

local app_desc = ffi.new("sapp_desc[1]")
app_desc[0].init_cb     = init
app_desc[0].frame_cb    = frame
app_desc[0].cleanup_cb  = cleanup
app_desc[0].event_cb    = input
app_desc[0].width       = width
app_desc[0].height      = height
app_desc[0].high_dpi    = true
app_desc[0].window_title = "Dim"
app_desc[0].fullscreen  = false
-- app_desc[0].icon.sokol_default = true 
app_desc[0].enable_clipboard = true
app_desc[0].ios_keyboard_resizes_canvas = false
app_desc[0].logger.func = slib.slog_func 

sapp.sapp_run( app_desc )

-- --------------------------------------------------------------------------------------

if(profile) then profile.stop() end

-- --------------------------------------------------------------------------------------